export enum RoleName {TECNICO, ADMINISTRADOR};

export enum MaterialTypes{HDD = "HDD", PORTATIL = "PORTATIL", PC = "PC", SERVIDOR = "SERVIDOR", TFT = "TFT", TELEFONO = "TELEFONO", TABLET = "TABLET", IMPRESORA = "IMPRESORA", CAJA_VARIOS = "CAJA VARIOS"};

export enum StateName {SOLICITADO, RECIBIDO, PRODUCCION, PROCESADO, INFORME, FINALIZADO};
